[phases.setup]
nixPkgs = ["nodejs-18_x", "python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install requests beautifulsoup4"
]

[start]
cmd = "node server.js"
