[phases.setup]
nixPkgs = ["nodejs-18_x", "python310"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install requests beautifulsoup4"
]

[start]
cmd = ". /opt/venv/bin/activate && node server.js"
